In [1]:
import pandas as pd
import json
import requests
import warnings
warnings.filterwarnings('ignore')

In [2]:
url = 'http://ergast.com/api/f1/2022/22.json'
response = requests.get(url)

In [3]:
content=json.loads(response.content)

In [4]:
df_results_2022=pd.DataFrame()
for race in range(1,23):
    url='http://ergast.com/api/f1/2022/{}/results.json'
    response=requests.get(url.format(race))
    content=json.loads(response.content)
    df_results_2022 = df_results_2022.append(content['MRData']['RaceTable']['Races'][0]['Results'])

In [5]:
df_results_2022

,number,position,positionText,points,Driver,Constructor,grid,laps,status,Time,FastestLap
0,16,1,1,26,"{'driverId': 'leclerc', 'permanentNumber': '16...","{'constructorId': 'ferrari', 'url': 'http://en...",1,57,Finished,"{'millis': '5853584', 'time': '1:37:33.584'}","{'rank': '1', 'lap': '51', 'Time': {'time': '1..."
1,55,2,2,18,"{'driverId': 'sainz', 'permanentNumber': '55',...","{'constructorId': 'ferrari', 'url': 'http://en...",3,57,Finished,"{'millis': '5859182', 'time': '+5.598'}","{'rank': '3', 'lap': '52', 'Time': {'time': '1..."
2,44,3,3,15,"{'driverId': 'hamilton', 'permanentNumber': '4...","{'constructorId': 'mercedes', 'url': 'http://e...",5,57,Finished,"{'millis': '5863259', 'time': '+9.675'}","{'rank': '5', 'lap': '53', 'Time': {'time': '1..."
3,63,4,4,12,"{'driverId': 'russell', 'permanentNumber': '63...","{'constructorId': 'mercedes', 'url': 'http://e...",9,57,Finished,"{'millis': '5864795', 'time': '+11.211'}","{'rank': '6', 'lap': '56', 'Time': {'time': '1..."
4,20,5,5,10,"{'driverId': 'kevin_magnussen', 'permanentNumb...","{'constructorId': 'haas', 'url': 'http://en.wi...",7,57,Finished,"{'millis': '5868338', 'time': '+14.754'}","{'rank': '8', 'lap': '53', 'Time': {'time': '1..."
...,...,...,...,...,...,...,...,...,...,...,...
15,47,16,16,0,"{'driverId': 'mick_schumacher', 'permanentNumb...","{'constructorId': 'haas', 'url': 'http://en.wi...",12,57,+1 Lap,NaN,"{'rank': '12', 'lap': '39', 'Time': {'time': '..."
16,20,17,17,0,"{'driverId': 'kevin_magnussen', 'permanentNumb...","{'constructorId': 'haas', 'url': 'http://en.wi...",16,57,+1 Lap,NaN,"{'rank': '20', 'lap': '40', 'Time': {'time': '..."
17,44,18,18,0,"{'driverId': 'hamilton', 'permanentNumber': '4...","{'constructorId': 'mercedes', 'url': 'http://e...",5,55,Hydraulics,NaN,"{'rank': '11', 'lap': '42', 'Time': {'time': '..."
18,6,19,19,0,"{'driverId': 'latifi', 'permanentNumber': '6',...","{'constructorId': 'williams', 'url': 'http://e...",20,55,Collision damage,NaN,"{'rank': '14', 'lap': '45', 'Time': {'time': '..."
19,14,20,R,0,"{'driverId': 'alonso', 'permanentNumber': '14'...","{'constructorId': 'alpine', 'url': 'http://en....",10,27,Water leak,NaN,"{'rank': '17', 'lap': '24', 'Time': {'time': '..."

In [6]:
df_results_2022['points']=df_results_2022.points.astype(int)

In [7]:
Conductores=df_results_2022['Driver'].apply(lambda x: x['driverId'])
Conductores

0             leclerc
1               sainz
2            hamilton
3             russell
4     kevin_magnussen
           ...
15    mick_schumacher
16    kevin_magnussen
17           hamilton
18             latifi
19             alonso
Name: Driver, Length: 440, dtype: object

## Actividad
Sumaremos los puntos obtenidos por conductor
### Tabla de resultados

In [8]:
df_results_2022['Driver']=df_results_2022['Driver'].apply(lambda x: x['driverId'])

In [9]:
df_results_2022['points']=df_results_2022['points'].astype(int)
df_results_2022

,number,position,positionText,points,Driver,Constructor,grid,laps,status,Time,FastestLap
0,16,1,1,26,leclerc,"{'constructorId': 'ferrari', 'url': 'http://en...",1,57,Finished,"{'millis': '5853584', 'time': '1:37:33.584'}","{'rank': '1', 'lap': '51', 'Time': {'time': '1..."
1,55,2,2,18,sainz,"{'constructorId': 'ferrari', 'url': 'http://en...",3,57,Finished,"{'millis': '5859182', 'time': '+5.598'}","{'rank': '3', 'lap': '52', 'Time': {'time': '1..."
2,44,3,3,15,hamilton,"{'constructorId': 'mercedes', 'url': 'http://e...",5,57,Finished,"{'millis': '5863259', 'time': '+9.675'}","{'rank': '5', 'lap': '53', 'Time': {'time': '1..."
3,63,4,4,12,russell,"{'constructorId': 'mercedes', 'url': 'http://e...",9,57,Finished,"{'millis': '5864795', 'time': '+11.211'}","{'rank': '6', 'lap': '56', 'Time': {'time': '1..."
4,20,5,5,10,kevin_magnussen,"{'constructorId': 'haas', 'url': 'http://en.wi...",7,57,Finished,"{'millis': '5868338', 'time': '+14.754'}","{'rank': '8', 'lap': '53', 'Time': {'time': '1..."
...,...,...,...,...,...,...,...,...,...,...,...
15,47,16,16,0,mick_schumacher,"{'constructorId': 'haas', 'url': 'http://en.wi...",12,57,+1 Lap,NaN,"{'rank': '12', 'lap': '39', 'Time': {'time': '..."
16,20,17,17,0,kevin_magnussen,"{'constructorId': 'haas', 'url': 'http://en.wi...",16,57,+1 Lap,NaN,"{'rank': '20', 'lap': '40', 'Time': {'time': '..."
17,44,18,18,0,hamilton,"{'constructorId': 'mercedes', 'url': 'http://e...",5,55,Hydraulics,NaN,"{'rank': '11', 'lap': '42', 'Time': {'time': '..."
18,6,19,19,0,latifi,"{'constructorId': 'williams', 'url': 'http://e...",20,55,Collision damage,NaN,"{'rank': '14', 'lap': '45', 'Time': {'time': '..."
19,14,20,R,0,alonso,"{'constructorId': 'alpine', 'url': 'http://en....",10,27,Water leak,NaN,"{'rank': '17', 'lap': '24', 'Time': {'time': '..."

In [10]:
df_results_2022.groupby(['Driver']).agg({'points':'sum'}).sort_values(by='points',ascending=False)

                 points
Driver
max_verstappen      433
perez               291
leclerc             291
russell             262
hamilton            233
sainz               228
norris              116
ocon                 89
alonso               81
bottas               47
vettel               37
ricciardo            34
gasly                23
kevin_magnussen      21
stroll               18
tsunoda              12
mick_schumacher      12
zhou                  6
albon                 4
latifi                2
de_vries              2
hulkenberg            0

## Ejercicio
Ahora lo haremos pero por constructor

In [11]:
df_results_2022['Constructor']=df_results_2022['Constructor'].apply(lambda x: x['constructorId'])

In [12]:
df_results_2022.groupby(['Constructor']).agg({'points':'sum'}).sort_values(by='points',ascending=False)

              points
Constructor
red_bull         724
ferrari          519
mercedes         495
alpine           170
mclaren          150
aston_martin      55
alfa              53
alphatauri        35
haas              33
williams           8

In [13]:
df_results_2022['Constructor']

0      ferrari
1      ferrari
2     mercedes
3     mercedes
4         haas
        ...
15        haas
16        haas
17    mercedes
18    williams
19      alpine
Name: Constructor, Length: 440, dtype: object

## Todas las carreras desde el 2010

In [14]:
url = 'http://ergast.com/api/f1/2012.json'
response = requests.get(url.format(race))
content=json.loads(response.content)

In [15]:
pd.DataFrame(content['MRData']['RaceTable']['Races'])

,season,round,url,raceName,Circuit,date,time
0,2012,1,http://en.wikipedia.org/wiki/2012_Australian_G...,Australian Grand Prix,"{'circuitId': 'albert_park', 'url': 'http://en...",2012-03-18,06:00:00Z
1,2012,2,http://en.wikipedia.org/wiki/2012_Malaysian_Gr...,Malaysian Grand Prix,"{'circuitId': 'sepang', 'url': 'http://en.wiki...",2012-03-25,08:00:00Z
2,2012,3,http://en.wikipedia.org/wiki/2012_Chinese_Gran...,Chinese Grand Prix,"{'circuitId': 'shanghai', 'url': 'http://en.wi...",2012-04-15,07:00:00Z
3,2012,4,http://en.wikipedia.org/wiki/2012_Bahrain_Gran...,Bahrain Grand Prix,"{'circuitId': 'bahrain', 'url': 'http://en.wik...",2012-04-22,12:00:00Z
4,2012,5,http://en.wikipedia.org/wiki/2012_Spanish_Gran...,Spanish Grand Prix,"{'circuitId': 'catalunya', 'url': 'http://en.w...",2012-05-13,12:00:00Z
5,2012,6,http://en.wikipedia.org/wiki/2012_Monaco_Grand...,Monaco Grand Prix,"{'circuitId': 'monaco', 'url': 'http://en.wiki...",2012-05-27,12:00:00Z
6,2012,7,http://en.wikipedia.org/wiki/2012_Canadian_Gra...,Canadian Grand Prix,"{'circuitId': 'villeneuve', 'url': 'http://en....",2012-06-10,18:00:00Z
7,2012,8,http://en.wikipedia.org/wiki/2012_European_Gra...,European Grand Prix,"{'circuitId': 'valencia', 'url': 'http://en.wi...",2012-06-24,12:00:00Z
8,2012,9,http://en.wikipedia.org/wiki/2012_British_Gran...,British Grand Prix,"{'circuitId': 'silverstone', 'url': 'http://en...",2012-07-08,12:00:00Z
9,2012,10,http://en.wikipedia.org/wiki/2012_German_Grand...,German Grand Prix,"{'circuitId': 'hockenheimring', 'url': 'http:/...",2012-07-22,12:00:00Z
10,2012,11,http://en.wikipedia.org/wiki/2012_Hungarian_Gr...,Hungarian Grand Prix,"{'circuitId': 'hungaroring', 'url': 'http://en...",2012-07-29,12:00:00Z
11,2012,12,http://en.wikipedia.org/wiki/2012_Belgian_Gran...,Belgian Grand Prix,"{'circuitId': 'spa', 'url': 'http://en.wikiped...",2012-09-02,12:00:00Z
12,2012,13,http://en.wikipedia.org/wiki/2012_Italian_Gran...,Italian Grand Prix,"{'circuitId': 'monza', 'url': 'http://en.wikip...",2012-09-09,12:00:00Z
13,2012,14,http://en.wikipedia.org/wiki/2012_Singapore_Gr...,Singapore Grand Prix,"{'circuitId': 'marina_bay', 'url': 'http://en....",2012-09-23,12:00:00Z
14,2012,15,http://en.wikipedia.org/wiki/2012_Japanese_Gra...,Japanese Grand Prix,"{'circuitId': 'suzuka', 'url': 'http://en.wiki...",2012-10-07,06:00:00Z
15,2012,16,http://en.wikipedia.org/wiki/2012_Korean_Grand...,Korean Grand Prix,"{'circuitId': 'yeongam', 'url': 'http://en.wik...",2012-10-14,06:00:00Z
16,2012,17,http://en.wikipedia.org/wiki/2012_Indian_Grand...,Indian Grand Prix,"{'circuitId': 'buddh', 'url': 'http://en.wikip...",2012-10-28,09:30:00Z
17,2012,18,http://en.wikipedia.org/wiki/2012_Abu_Dhabi_Gr...,Abu Dhabi Grand Prix,"{'circuitId': 'yas_marina', 'url': 'http://en....",2012-11-04,13:00:00Z
18,2012,19,http://en.wikipedia.org/wiki/2012_United_State...,United States Grand Prix,"{'circuitId': 'americas', 'url': 'http://en.wi...",2012-11-18,19:00:00Z
19,2012,20,http://en.wikipedia.org/wiki/2012_Brazilian_Gr...,Brazilian Grand Prix,"{'circuitId': 'interlagos', 'url': 'http://en....",2012-11-25,16:00:00Z

In [16]:
races = {'season':[],
        'round':[],
        'raceName':[],
        'circuitId':[],
        'lat':[],
        'long':[],
        'country':[],
        'date':[],
        'url':[]}

In [17]:
for year in range(2010,2023):
    url='http://ergast.com/api/f1/{}.json'
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    
    for item in content['MRData']['RaceTable']['Races']:
            races['season'].append(int(item['season']))
            races['round'].append(int(item['round']))
            races['raceName'].append(item['raceName'])
            races['circuitId'].append(item['Circuit']['circuitId'])
            races['lat'].append(item['Circuit']['Location']['lat'])
            races['long'].append(item['Circuit']['Location']['long'])
            races['country'].append(item['Circuit']['Location']['country'])
            races['date'].append(item['date'])
            #races['url'].append(item['Circuit']['url'])
            races['url'].append(item['url'])

In [18]:
pd.DataFrame(races)

,season,round,raceName,circuitId,lat,long,country,date,url
0,2010,1,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2010-03-14,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...
1,2010,2,Australian Grand Prix,albert_park,-37.8497,144.968,Australia,2010-03-28,http://en.wikipedia.org/wiki/2010_Australian_G...
2,2010,3,Malaysian Grand Prix,sepang,2.76083,101.738,Malaysia,2010-04-04,http://en.wikipedia.org/wiki/2010_Malaysian_Gr...
3,2010,4,Chinese Grand Prix,shanghai,31.3389,121.22,China,2010-04-18,http://en.wikipedia.org/wiki/2010_Chinese_Gran...
4,2010,5,Spanish Grand Prix,catalunya,41.57,2.26111,Spain,2010-05-09,http://en.wikipedia.org/wiki/2010_Spanish_Gran...
...,...,...,...,...,...,...,...,...,...
254,2022,18,Japanese Grand Prix,suzuka,34.8431,136.541,Japan,2022-10-09,http://en.wikipedia.org/wiki/2022_Japanese_Gra...
255,2022,19,United States Grand Prix,americas,30.1328,-97.6411,USA,2022-10-23,http://en.wikipedia.org/wiki/2022_United_State...
256,2022,20,Mexico City Grand Prix,rodriguez,19.4042,-99.0907,Mexico,2022-10-30,http://en.wikipedia.org/wiki/2022_Mexican_Gran...
257,2022,21,Brazilian Grand Prix,interlagos,-23.7036,-46.6997,Brazil,2022-11-13,http://en.wikipedia.org/wiki/2022_Brazilian_Gr...
258,2022,22,Abu Dhabi Grand Prix,yas_marina,24.4672,54.6031,UAE,2022-11-20,http://en.wikipedia.org/wiki/2022_Abu_Dhabi_Gr...

## Actividad
Tabla con year y url

In [22]:
url='http://ergast.com/api/f1/seasons.json'
response = requests.get(url)
content=json.loads(response.content)

In [24]:
season ={'temporada':[],'url':[]}
for item in content['MRData']['SeasonTable']['Seasons']:
    season['temporada'].append(int(item['season']))
    season['url'].append(item['url'])
pd.DataFrame(season)

    temporada                                                url
0        1950  http://en.wikipedia.org/wiki/1950_Formula_One_...
1        1951  http://en.wikipedia.org/wiki/1951_Formula_One_...
2        1952  http://en.wikipedia.org/wiki/1952_Formula_One_...
3        1953  http://en.wikipedia.org/wiki/1953_Formula_One_...
4        1954  http://en.wikipedia.org/wiki/1954_Formula_One_...
5        1955  http://en.wikipedia.org/wiki/1955_Formula_One_...
6        1956  http://en.wikipedia.org/wiki/1956_Formula_One_...
7        1957  http://en.wikipedia.org/wiki/1957_Formula_One_...
8        1958  http://en.wikipedia.org/wiki/1958_Formula_One_...
9        1959  http://en.wikipedia.org/wiki/1959_Formula_One_...
10       1960  http://en.wikipedia.org/wiki/1960_Formula_One_...
11       1961  http://en.wikipedia.org/wiki/1961_Formula_One_...
12       1962  http://en.wikipedia.org/wiki/1962_Formula_One_...
13       1963  http://en.wikipedia.org/wiki/1963_Formula_One_...
14       1964  http://en.wikipedia.org/wiki/1964_Formula_One_...
15       1965  http://en.wikipedia.org/wiki/1965_Formula_One_...
16       1966  http://en.wikipedia.org/wiki/1966_Formula_One_...
17       1967  http://en.wikipedia.org/wiki/1967_Formula_One_...
18       1968  http://en.wikipedia.org/wiki/1968_Formula_One_...
19       1969  http://en.wikipedia.org/wiki/1969_Formula_One_...
20       1970  http://en.wikipedia.org/wiki/1970_Formula_One_...
21       1971  http://en.wikipedia.org/wiki/1971_Formula_One_...
22       1972  http://en.wikipedia.org/wiki/1972_Formula_One_...
23       1973  http://en.wikipedia.org/wiki/1973_Formula_One_...
24       1974  http://en.wikipedia.org/wiki/1974_Formula_One_...
25       1975  http://en.wikipedia.org/wiki/1975_Formula_One_...
26       1976  http://en.wikipedia.org/wiki/1976_Formula_One_...
27       1977  http://en.wikipedia.org/wiki/1977_Formula_One_...
28       1978  http://en.wikipedia.org/wiki/1978_Formula_One_...
29       1979  http://en.wikipedia.org/wiki/1979_Formula_One_...

### Exportar a excel o csv
La diferencia con excel serÃ­a:

pd.DataFrame(races).to_excel('races.xlsx',index=False)

In [25]:
pd.DataFrame(races).to_csv('races.csv',index=False)

In [26]:
pd.DataFrame(season).to_csv('season.csv',index=False)

# Tarea 1
Crear el scrip que genere 4 archivos csv que contengan la informaciÃ³n de las siguientes tablas:

drivers constructors circuits qualifying

### Drivers

In [4]:
for year in range(2010,2023):
    url='http://ergast.com/api/f1/{}/drivers.json'
    response=requests.get(url.format(year))
    content=json.loads(response.content)

In [9]:
#drivers ={'driverId':[],'driverRef':[],'number':[],'code':[],'forname':[],'sumame':[],'dob':[],'nationality':[],'url':[]}
drivers ={'driverId':[],'number':[],'code':[],'forname':[],'sumame':[],'dob':[],'nationality':[],'url':[]}
for item in content['MRData']['DriverTable']['Drivers']:
    drivers['driverId'].append(item['driverId'])
    #drivers['driverRef'].append(item['driverRef'])
    drivers['number'].append(int(item['permanentNumber']))
    drivers['code'].append(item['code'])
    drivers['forname'].append(item['familyName'])
    drivers['sumame'].append(item['givenName'])
    drivers['dob'].append(item['dateOfBirth'])
    drivers['nationality'].append(item['nationality'])
    drivers['url'].append(item['url'])
pd.DataFrame(drivers)

,driverId,number,code,forname,sumame,dob,nationality,url
0,albon,23,ALB,Albon,Alexander,1996-03-23,Thai,http://en.wikipedia.org/wiki/Alexander_Albon
1,alonso,14,ALO,Alonso,Fernando,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
2,bottas,77,BOT,Bottas,Valtteri,1989-08-28,Finnish,http://en.wikipedia.org/wiki/Valtteri_Bottas
3,de_vries,45,DEV,de Vries,Nyck,1995-02-06,Dutch,http://en.wikipedia.org/wiki/Nyck_de_Vries
4,gasly,10,GAS,Gasly,Pierre,1996-02-07,French,http://en.wikipedia.org/wiki/Pierre_Gasly
5,hamilton,44,HAM,Hamilton,Lewis,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
6,hulkenberg,27,HUL,HÃ¼lkenberg,Nico,1987-08-19,German,http://en.wikipedia.org/wiki/Nico_H%C3%BClkenberg
7,latifi,6,LAT,Latifi,Nicholas,1995-06-29,Canadian,http://en.wikipedia.org/wiki/Nicholas_Latifi
8,leclerc,16,LEC,Leclerc,Charles,1997-10-16,Monegasque,http://en.wikipedia.org/wiki/Charles_Leclerc
9,kevin_magnussen,20,MAG,Magnussen,Kevin,1992-10-05,Danish,http://en.wikipedia.org/wiki/Kevin_Magnussen
10,norris,4,NOR,Norris,Lando,1999-11-13,British,http://en.wikipedia.org/wiki/Lando_Norris
11,ocon,31,OCO,Ocon,Esteban,1996-09-17,French,http://en.wikipedia.org/wiki/Esteban_Ocon
12,perez,11,PER,PÃ©rez,Sergio,1990-01-26,Mexican,http://en.wikipedia.org/wiki/Sergio_P%C3%A9rez
13,ricciardo,3,RIC,Ricciardo,Daniel,1989-07-01,Australian,http://en.wikipedia.org/wiki/Daniel_Ricciardo
14,russell,63,RUS,Russell,George,1998-02-15,British,http://en.wikipedia.org/wiki/George_Russell_%2...
15,sainz,55,SAI,Sainz,Carlos,1994-09-01,Spanish,http://en.wikipedia.org/wiki/Carlos_Sainz_Jr.
16,mick_schumacher,47,MSC,Schumacher,Mick,1999-03-22,German,http://en.wikipedia.org/wiki/Mick_Schumacher
17,stroll,18,STR,Stroll,Lance,1998-10-29,Canadian,http://en.wikipedia.org/wiki/Lance_Stroll
18,tsunoda,22,TSU,Tsunoda,Yuki,2000-05-11,Japanese,http://en.wikipedia.org/wiki/Yuki_Tsunoda
19,max_verstappen,33,VER,Verstappen,Max,1997-09-30,Dutch,http://en.wikipedia.org/wiki/Max_Verstappen
20,vettel,5,VET,Vettel,Sebastian,1987-07-03,German,http://en.wikipedia.org/wiki/Sebastian_Vettel
21,zhou,24,ZHO,Zhou,Guanyu,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Guanyu_Zhou

In [ ]:
pd.DataFrame(drivers).to_csv('drivers.csv',index=False)

### constructors

In [12]:
for year in range(2010,2023):
    url='http://ergast.com/api/f1/{}/constructors.json'
    response=requests.get(url.format(year))
    content=json.loads(response.content)

In [14]:
#constructors ={'constructorId':[],'constructorRef':[],'name':[],'nationality':[],'url':[]}
constructors ={'constructorId':[],'name':[],'nationality':[],'url':[]}
for item in content['MRData']['ConstructorTable']['Constructors']:
    constructors['constructorId'].append(item['constructorId'])
    #constructors['driverRef'].append(item['driverRef'])
    constructors['name'].append(item['name'])
    constructors['nationality'].append(item['nationality'])
    constructors['url'].append(item['url'])
pd.DataFrame(constructors)

,constructorId,name,nationality,url
0,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...
1,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
2,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team
3,aston_martin,Aston Martin,British,http://en.wikipedia.org/wiki/Aston_Martin_in_F...
4,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari
5,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
6,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
7,mercedes,Mercedes,German,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...
8,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing
9,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...

In [ ]:
pd.DataFrame(constructors).to_csv('constructors.csv',index=False)

### circuits

In [66]:
for year in range(2010,2023):
    url='http://ergast.com/api/f1/{}/circuits.json'
    response=requests.get(url.format(year))
    content=json.loads(response.content)

In [67]:
content['MRData']['CircuitTable']['Circuits'].keys()

AttributeError: 'list' object has no attribute 'keys'

In [44]:
#cicuits ={'circuitId':[],'cicuitsRef':[],'name':[],'location':[],'country':[],'lat':[],'lng':[],'alt':[],'url':[]}
circuits ={'circuitId':[],'name':[],'location':[],'country':[],'lat':[],'lng':[],'url':[]}
for item in content['MRData']['CircuitTable']['Circuits']:
    circuits['circuitId'].append(item['circuitId'])
    #circuits['driverRef'].append(item['driverRef'])
    circuits['lat'].append(float(item['Location']['lat']))
    circuits['lng'].append(float(item['Location']['long']))
    circuits['location'].append(item['Location']['locality'])
    circuits['country'].append(item['Location']['country'])
    #circuits['alt'].append(item['Location']['alt'])
    circuits['name'].append(item['circuitName'])
    circuits['url'].append(item['url'])
pd.DataFrame(circuits)

,circuitId,name,location,country,lat,lng,url
0,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.96800,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,americas,Circuit of the Americas,Austin,USA,30.1328,-97.64110,http://en.wikipedia.org/wiki/Circuit_of_the_Am...
2,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.51060,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,baku,Baku City Circuit,Baku,Azerbaijan,40.3725,49.85330,http://en.wikipedia.org/wiki/Baku_City_Circuit
4,catalunya,Circuit de Barcelona-Catalunya,MontmelÃ³,Spain,41.5700,2.26111,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
5,hungaroring,Hungaroring,Budapest,Hungary,47.5789,19.24860,http://en.wikipedia.org/wiki/Hungaroring
6,imola,Autodromo Enzo e Dino Ferrari,Imola,Italy,44.3439,11.71670,http://en.wikipedia.org/wiki/Autodromo_Enzo_e_...
7,interlagos,AutÃ³dromo JosÃ© Carlos Pace,SÃ£o Paulo,Brazil,-23.7036,-46.69970,http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jo...
8,jeddah,Jeddah Corniche Circuit,Jeddah,Saudi Arabia,21.6319,39.10440,http://en.wikipedia.org/wiki/Jeddah_Street_Cir...
9,marina_bay,Marina Bay Street Circuit,Marina Bay,Singapore,1.2914,103.86400,http://en.wikipedia.org/wiki/Marina_Bay_Street...
10,miami,Miami International Autodrome,Miami,USA,25.9581,-80.23890,http://en.wikipedia.org/wiki/Miami_Internation...
11,monaco,Circuit de Monaco,Monte-Carlo,Monaco,43.7347,7.42056,http://en.wikipedia.org/wiki/Circuit_de_Monaco
12,monza,Autodromo Nazionale di Monza,Monza,Italy,45.6156,9.28111,http://en.wikipedia.org/wiki/Autodromo_Naziona...
13,red_bull_ring,Red Bull Ring,Spielberg,Austria,47.2197,14.76470,http://en.wikipedia.org/wiki/Red_Bull_Ring
14,ricard,Circuit Paul Ricard,Le Castellet,France,43.2506,5.79167,http://en.wikipedia.org/wiki/Paul_Ricard_Circuit
15,rodriguez,AutÃ³dromo Hermanos RodrÃ­guez,Mexico City,Mexico,19.4042,-99.09070,http://en.wikipedia.org/wiki/Aut%C3%B3dromo_He...
16,silverstone,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,http://en.wikipedia.org/wiki/Silverstone_Circuit
17,spa,Circuit de Spa-Francorchamps,Spa,Belgium,50.4372,5.97139,http://en.wikipedia.org/wiki/Circuit_de_Spa-Fr...
18,suzuka,Suzuka Circuit,Suzuka,Japan,34.8431,136.54100,http://en.wikipedia.org/wiki/Suzuka_Circuit
19,villeneuve,Circuit Gilles Villeneuve,Montreal,Canada,45.5000,-73.52280,http://en.wikipedia.org/wiki/Circuit_Gilles_Vi...
20,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.60310,http://en.wikipedia.org/wiki/Yas_Marina_Circuit
21,zandvoort,Circuit Park Zandvoort,Zandvoort,Netherlands,52.3888,4.54092,http://en.wikipedia.org/wiki/Circuit_Zandvoort

In [ ]:
pd.DataFrame(circuits).to_csv('circuits.csv',index=False)

### qualifying

In [102]:
for year in range(2010,2023):
    url='http://ergast.com/api/f1/{}/qualifying.json'
    response=requests.get(url.format(year))
    content=json.loads(response.content)

In [103]:
#qualifying ={'qualifyingId':[],'raceId':[],'driverId':[],'constructorId':[],'number':[],'position':[],'Q1':[],'Q2':[],'Q3':[]}
qualifying ={'driverId':[],'constructorId':[],'number':[],'position':[],'Q1':[],'Q2':[],'Q3':[]}
for item in content['MRData']['RaceTable']['Races'][0]['QualifyingResults']:
    #qualifying['qualifyingId'].append(item['qualifyingId'])
    #qualifying['raceId'].append(item['driverRef'])
    qualifying['driverId'].append(item['Driver']['driverId'])
    qualifying['constructorId'].append(item['Constructor']['constructorId'])
    qualifying['number'].append(int(item['number']))
    qualifying['position'].append(int(item['position']))
    qualifying['Q1'].append(item['Q1'])
    qualifying['Q2'].append(item['Q2'])
    qualifying['Q3'].append(item['Q3'])
for item in content['MRData']['RaceTable']['Races'][1]['QualifyingResults']:
    #qualifying['qualifyingId'].append(item['qualifyingId'])
    #qualifying['raceId'].append(item['driverRef'])
    qualifying['driverId'].append(item['Driver']['driverId'])
    qualifying['constructorId'].append(item['Constructor']['constructorId'])
    qualifying['number'].append(int(item['number']))
    qualifying['position'].append(int(item['position']))
    qualifying['Q1'].append(item['Q1'])
    qualifying['Q2'].append(item['Q2'])
    qualifying['Q3'].append(item['Q3'])
pd.DataFrame(qualifying)

KeyError: 'Q3'

In [100]:
content['MRData']['RaceTable']['Races'][0]['QualifyingResults'][0].keys()

dict_keys(['number', 'position', 'Driver', 'Constructor', 'Q1', 'Q2', 'Q3'])

In [ ]:
pd.DataFrame(qualifying).to_csv('qualifying.csv',index=False)