In [1]:
import pandas as pd
import numpy as np
import json
import requests
import warnings
warnings.filterwarnings('ignore')

# Tarea 1
Crear el scrip que genere 4 archivos csv que contengan la información de las siguientes tablas:

drivers constructors circuits qualifying

### Drivers

In [63]:
drivers ={'year':[],'driverId':[],'number':[],'code':[],'forname':[],'sumame':[],'dob':[],'nationality':[],'url':[]}
for year in list(range(2010,2023)):
    url='http://ergast.com/api/f1/{}/drivers.json'
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    for item in content['MRData']['DriverTable']['Drivers']:
        drivers['year'].append(year)
        drivers['driverId'].append(item['driverId'])
        try:
            drivers['number'].append(int(item['permanentNumber']))
        except:
            drivers['number'].append(None)
        drivers['code'].append(item['code'])
        drivers['forname'].append(item['familyName'])
        drivers['sumame'].append(item['givenName'])
        drivers['dob'].append(item['dateOfBirth'])
        drivers['nationality'].append(item['nationality'])
        drivers['url'].append(item['url'])
drivers['driverRef']=np.arange(1,pd.DataFrame(drivers).shape[0]+1,1)
pd.DataFrame(drivers)

,year,driverId,number,code,forname,sumame,dob,nationality,url,driverRef
0,2010,alguersuari,NaN,ALG,Alguersuari,Jaime,1990-03-23,Spanish,http://en.wikipedia.org/wiki/Jaime_Alguersuari,1
1,2010,alonso,14.0,ALO,Alonso,Fernando,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,2
2,2010,barrichello,NaN,BAR,Barrichello,Rubens,1972-05-23,Brazilian,http://en.wikipedia.org/wiki/Rubens_Barrichello,3
3,2010,buemi,NaN,BUE,Buemi,Sébastien,1988-10-31,Swiss,http://en.wikipedia.org/wiki/S%C3%A9bastien_Buemi,4
4,2010,button,22.0,BUT,Button,Jenson,1980-01-19,British,http://en.wikipedia.org/wiki/Jenson_Button,5
...,...,...,...,...,...,...,...,...,...,...
299,2022,stroll,18.0,STR,Stroll,Lance,1998-10-29,Canadian,http://en.wikipedia.org/wiki/Lance_Stroll,300
300,2022,tsunoda,22.0,TSU,Tsunoda,Yuki,2000-05-11,Japanese,http://en.wikipedia.org/wiki/Yuki_Tsunoda,301
301,2022,max_verstappen,33.0,VER,Verstappen,Max,1997-09-30,Dutch,http://en.wikipedia.org/wiki/Max_Verstappen,302
302,2022,vettel,5.0,VET,Vettel,Sebastian,1987-07-03,German,http://en.wikipedia.org/wiki/Sebastian_Vettel,303
303,2022,zhou,24.0,ZHO,Zhou,Guanyu,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Guanyu_Zhou,304

In [64]:
pd.DataFrame(drivers).to_csv('drivers.csv',index=False)

### constructors

In [65]:
#constructors ={'constructorId':[],'constructorRef':[],'name':[],'nationality':[],'url':[]}
constructors ={'year':[],'constructorRef':[],'constructorId':[],'name':[],'nationality':[],'url':[]}
for year in range(2010,2023):
    url='http://ergast.com/api/f1/{}/constructors.json'
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    for item in content['MRData']['ConstructorTable']['Constructors']:
        constructors['year'].append(year)
        constructors['constructorId'].append(item['constructorId'])
        constructors['name'].append(item['name'])
        constructors['nationality'].append(item['nationality'])
        constructors['url'].append(item['url'])
constructors['constructorRef']=np.arange(1,140,1)
pd.DataFrame(constructors)

,year,constructorRef,constructorId,name,nationality,url
0,2010,1,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari
1,2010,2,force_india,Force India,Indian,http://en.wikipedia.org/wiki/Racing_Point_Forc...
2,2010,3,hrt,HRT,Spanish,http://en.wikipedia.org/wiki/Hispania_Racing
3,2010,4,lotus_racing,Lotus,Malaysian,http://en.wikipedia.org/wiki/Lotus_Racing
4,2010,5,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
...,...,...,...,...,...,...
134,2022,135,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
135,2022,136,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
136,2022,137,mercedes,Mercedes,German,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...
137,2022,138,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing
138,2022,139,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...

In [66]:
pd.DataFrame(constructors).to_csv('constructors.csv',index=False)

### circuits

In [67]:
circuits ={'year':[],'circuitId':[],'cicuitsRef':[],'name':[],'location':[],'country':[],'lat':[],'lng':[],'url':[]}
for year in range(2010,2023):
    url='http://ergast.com/api/f1/{}/circuits.json'
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    for item in content['MRData']['CircuitTable']['Circuits']:
        circuits['year'].append(year)
        circuits['circuitId'].append(item['circuitId'])
        #circuits['driverRef'].append(item['driverRef'])
        circuits['lat'].append(float(item['Location']['lat']))
        circuits['lng'].append(float(item['Location']['long']))
        circuits['location'].append(item['Location']['locality'])
        circuits['country'].append(item['Location']['country'])
        #circuits['alt'].append(item['Location']['alt'])
        circuits['name'].append(item['circuitName'])
        circuits['url'].append(item['url'])
circuits['cicuitsRef']=np.arange(1,256,1)
pd.DataFrame(circuits)

,year,circuitId,cicuitsRef,name,location,country,lat,lng,url
0,2010,albert_park,1,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.96800,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2010,bahrain,2,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.51060,http://en.wikipedia.org/wiki/Bahrain_Internati...
2,2010,catalunya,3,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.5700,2.26111,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
3,2010,hockenheimring,4,Hockenheimring,Hockenheim,Germany,49.3278,8.56583,http://en.wikipedia.org/wiki/Hockenheimring
4,2010,hungaroring,5,Hungaroring,Budapest,Hungary,47.5789,19.24860,http://en.wikipedia.org/wiki/Hungaroring
...,...,...,...,...,...,...,...,...,...
250,2022,spa,251,Circuit de Spa-Francorchamps,Spa,Belgium,50.4372,5.97139,http://en.wikipedia.org/wiki/Circuit_de_Spa-Fr...
251,2022,suzuka,252,Suzuka Circuit,Suzuka,Japan,34.8431,136.54100,http://en.wikipedia.org/wiki/Suzuka_Circuit
252,2022,villeneuve,253,Circuit Gilles Villeneuve,Montreal,Canada,45.5000,-73.52280,http://en.wikipedia.org/wiki/Circuit_Gilles_Vi...
253,2022,yas_marina,254,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.60310,http://en.wikipedia.org/wiki/Yas_Marina_Circuit
254,2022,zandvoort,255,Circuit Park Zandvoort,Zandvoort,Netherlands,52.3888,4.54092,http://en.wikipedia.org/wiki/Circuit_Zandvoort

In [68]:
pd.DataFrame(circuits).to_csv('circuits.csv',index=False)

### qualifying

In [61]:
qualifying ={'year':[],'qualifyingId':[],'raceId':[],'driverId':[],'constructorId':[],'number':[],'position':[],'Q1':[],'Q2':[],'Q3':[]}
for year in range(2010,2023):
    url= 'http://ergast.com/api/f1/{}/qualifying.json'
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    
    for item in content['MRData']['RaceTable']['Races'][0]['QualifyingResults']:
        qualifying['year'].append(year)
        #qualifying['qualifyingId'].append(item['qualifyingId'])
        qualifying['raceId'].append(content['MRData']['RaceTable']['Races'][0]['raceName'])
        qualifying['driverId'].append(item['Driver']['driverId'])
        qualifying['constructorId'].append(item['Constructor']['constructorId'])
        qualifying['number'].append(int(item['number']))
        qualifying['position'].append(int(item['position']))
        qualifying['Q1'].append(item['Q1'])
        try:
            qualifying['Q2'].append(item['Q2'])
        except:
            qualifying['Q2'].append(None)
        try:
            qualifying['Q3'].append(item['Q3'])
        except:
            qualifying['Q3'].append(None)
    for item in content['MRData']['RaceTable']['Races'][1]['QualifyingResults']:
        qualifying['year'].append(year)
        #qualifying['qualifyingId'].append(item['qualifyingId'])
        qualifying['raceId'].append(content['MRData']['RaceTable']['Races'][1]['raceName'])
        qualifying['driverId'].append(item['Driver']['driverId'])
        qualifying['constructorId'].append(item['Constructor']['constructorId'])
        qualifying['number'].append(int(item['number']))
        qualifying['position'].append(int(item['position']))
        qualifying['Q1'].append(item['Q1'])
        try:
            qualifying['Q2'].append(item['Q2'])
        except:
            qualifying['Q2'].append(None)
        try:
            qualifying['Q3'].append(item['Q3'])
        except:
            qualifying['Q3'].append(None)
qualifying['qualifyingId']=np.arange(1,391,1)
pd.DataFrame(qualifying)

,year,qualifyingId,raceId,driverId,constructorId,number,position,Q1,Q2,Q3
0,2010,1,Bahrain Grand Prix,vettel,red_bull,5,1,1:55.029,1:53.883,1:54.101
1,2010,2,Bahrain Grand Prix,massa,ferrari,7,2,1:55.313,1:54.331,1:54.242
2,2010,3,Bahrain Grand Prix,alonso,ferrari,8,3,1:54.612,1:54.172,1:54.608
3,2010,4,Bahrain Grand Prix,hamilton,mclaren,2,4,1:55.341,1:54.707,1:55.217
4,2010,5,Bahrain Grand Prix,rosberg,mercedes,4,5,1:55.463,1:54.682,1:55.241
...,...,...,...,...,...,...,...,...,...,...
385,2022,386,Saudi Arabian Grand Prix,russell,mercedes,63,6,1:29.680,1:29.618,1:29.104
386,2022,387,Saudi Arabian Grand Prix,alonso,alpine,14,7,1:29.978,1:29.295,1:29.147
387,2022,388,Saudi Arabian Grand Prix,bottas,alfa,77,8,1:29.683,1:29.404,1:29.183
388,2022,389,Saudi Arabian Grand Prix,gasly,alphatauri,10,9,1:29.891,1:29.418,1:29.254
389,2022,390,Saudi Arabian Grand Prix,kevin_magnussen,haas,20,10,1:29.831,1:29.546,1:29.588

In [ ]:
pd.DataFrame(qualifying).to_csv('qualifying.csv',index=False)

# Tarea 2
Crear el scrip que genere 4 archivos csv que contengan la información de las siguientes tablas:

sprintResults status results pitStops

### sprintResults

In [156]:
sprintResult ={'year':[],'sprintResultId':[],'raceId':[],'driverId':[],'constructorId':[],'number':[],'grid':[],
               'position':[],'positionText':[],'points':[],'laps':[],'time':[],'milliseconds':[],
               'fastestLap':[],'fastestLapTime':[],'statusId':[]}
for year in range(2010,2023):
    url= 'http://ergast.com/api/f1/{}/sprint.json?limit=1000'
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    inicio=content['MRData']['RaceTable']
    for item in range(0,len(inicio['Races'])):
        for pivote in inicio['Races'][item]['SprintResults']:
            sprintResult['year'].append(year)
            sprintResult['raceId'].append(inicio['Races'][item]['raceName'])
            sprintResult['driverId'].append(pivote['Driver']['driverId'])
            sprintResult['constructorId'].append(pivote['Constructor']['constructorId'])
            sprintResult['number'].append(int(pivote['number']))
            sprintResult['grid'].append(pivote['grid'])
            sprintResult['position'].append(int(pivote['position']))
            sprintResult['positionText'].append((pivote['positionText']))
            sprintResult['points'].append(int(pivote['points']))
            sprintResult['laps'].append(int(pivote['laps']))
            try:
                sprintResult['time'].append(pivote['Time']['time'])
            except:
                sprintResult["time"].append(None)
            try:
                sprintResult['milliseconds'].append(pivote['Time']['millis'])
            except:
                sprintResult["milliseconds"].append(None)
            try:
                sprintResult['fastestLap'].append(int(pivote['FastestLap']['lap']))
            except:
                sprintResult["fastestLap"].append(None)
            try:
                sprintResult['fastestLapTime'].append(pivote['Time']['time'])
            except:
                sprintResult["fastestLapTime"].append(None)
            sprintResult['statusId'].append(pivote['status'])
sprintResult['sprintResultId']=np.arange(1,121,1)
pd.DataFrame(sprintResult)

,year,sprintResultId,raceId,driverId,constructorId,number,grid,position,positionText,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
0,2021,1,British Grand Prix,max_verstappen,red_bull,33,2,1,1,3,17,25:38.426,1538426,14.0,25:38.426,Finished
1,2021,2,British Grand Prix,hamilton,mercedes,44,1,2,2,2,17,+1.430,1539856,17.0,+1.430,Finished
2,2021,3,British Grand Prix,bottas,mercedes,77,3,3,3,1,17,+7.502,1545928,17.0,+7.502,Finished
3,2021,4,British Grand Prix,leclerc,ferrari,16,4,4,4,0,17,+11.278,1549704,16.0,+11.278,Finished
4,2021,5,British Grand Prix,norris,mclaren,4,6,5,5,0,17,+24.111,1562537,16.0,+24.111,Finished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2022,116,Brazilian Grand Prix,stroll,aston_martin,18,15,16,16,0,24,+50.700,1862007,4.0,+50.700,Finished
116,2022,117,Brazilian Grand Prix,ocon,alpine,31,6,17,17,0,24,+51.756,1863063,5.0,+51.756,Finished
117,2022,118,Brazilian Grand Prix,alonso,alpine,14,7,18,18,0,24,+53.985,1865292,5.0,+53.985,Finished
118,2022,119,Brazilian Grand Prix,latifi,williams,6,16,19,19,0,24,+1:16.850,1888157,4.0,+1:16.850,Finished
119,2022,120,Brazilian Grand Prix,albon,williams,23,11,20,R,0,12,None,None,4.0,None,Retired

In [157]:
pd.DataFrame(sprintResult).to_csv('sprintResult.csv',index=False)

### status

In [152]:
status ={'year':[],'statusId':[],'status':[]}
for year in range(2010,2023):
    url= 'http://ergast.com/api/f1/{}/status.json'
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    for item in content['MRData']['StatusTable']['Status']:
        status['year'].append(year)
        status['statusId'].append(item['statusId'])
        status['status'].append(item['status'])
pd.DataFrame(status)

     year statusId            status
0    2010        1          Finished
1    2010        3          Accident
2    2010        4         Collision
3    2010        5            Engine
4    2010        6           Gearbox
..    ...      ...               ...
356  2022      103        Water pump
357  2022      130  Collision damage
358  2022      131        Power Unit
359  2022      140         Undertray
360  2022      141    Cooling system

[361 rows x 3 columns]

In [153]:
pd.DataFrame(status).to_csv('status.csv',index=False)

### results

In [154]:
results = {'year':[],'resultsId':[], 
           'raceId':[],'driverId':[], 'constructorId':[],
           'number':[], 'grid':[],'position':[], 'positionText':[],
           'points':[],'laps':[], 'time':[], 'milliseconds':[],
           'fastestLap':[],'rank':[],'fastestLapTime':[],'statusId':[]}
for year in range(2010,2023):
    url= 'http://ergast.com/api/f1/{}/results.json?limit=1000'
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    for item in range(0,len(content['MRData']['RaceTable']['Races'])):
        for item2 in content['MRData']['RaceTable']['Races'][item]['Results']:
            results['year'].append(year)
            results['raceId'].append(content['MRData']['RaceTable']['Races'][item]['raceName'])
            results['driverId'].append(item2['Driver']['driverId'])
            results['constructorId'].append(item2['Constructor']['constructorId'])
            results['number'].append(int(item2['number']))
            results['grid'].append(item2['grid'])
            results['position'].append(int(item2['position']))
            results['positionText'].append(item2['positionText'])
            results['points'].append(float(item2['points']))
            results['laps'].append(int(item2['laps']))
            try:
                results['time'].append(item2['Time']['time'])
            except:
                results['time'].append(None)
            try:
                results['fastestLap'].append(item2['FastestLap']['lap'])
            except:
                results['fastestLap'].append(None)
            try:
                results['milliseconds'].append(item2['Time']['millis'])
            except:
                results['milliseconds'].append(None)
            try:
                results['rank'].append(item2['FastestLap']['rank'])
            except:
                results['rank'].append(None)
            try:
                results['fastestLapTime'].append(item2['FastestLap']['Time']['time'])
            except:
                results['fastestLapTime'].append(None)
            results['statusId'].append(item2['status'])
results['resultsId']=np.arange(1,5518,1)
pd.DataFrame(results)

,year,resultsId,raceId,driverId,constructorId,number,grid,position,positionText,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,statusId
0,2010,1,Bahrain Grand Prix,alonso,ferrari,8,3,1,1,25.0,49,1:39:20.396,5960396,45,1,1:58.287,Finished
1,2010,2,Bahrain Grand Prix,massa,ferrari,7,2,2,2,18.0,49,+16.099,5976495,38,5,1:59.732,Finished
2,2010,3,Bahrain Grand Prix,hamilton,mclaren,2,4,3,3,15.0,49,+23.182,5983578,42,4,1:59.560,Finished
3,2010,4,Bahrain Grand Prix,vettel,red_bull,5,1,4,4,12.0,49,+38.799,5999195,32,12,2:00.218,Finished
4,2010,5,Bahrain Grand Prix,rosberg,mercedes,4,5,5,5,10.0,49,+40.213,6000609,45,13,2:00.236,Finished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5512,2022,5513,Abu Dhabi Grand Prix,mick_schumacher,haas,47,12,16,16,0.0,57,None,None,39,12,1:29.833,+1 Lap
5513,2022,5514,Abu Dhabi Grand Prix,kevin_magnussen,haas,20,16,17,17,0.0,57,None,None,40,20,1:31.158,+1 Lap
5514,2022,5515,Abu Dhabi Grand Prix,hamilton,mercedes,44,5,18,18,0.0,55,None,None,42,11,1:29.788,Hydraulics
5515,2022,5516,Abu Dhabi Grand Prix,latifi,williams,6,20,19,19,0.0,55,None,None,45,14,1:30.309,Collision damage
5516,2022,5517,Abu Dhabi Grand Prix,alonso,alpine,14,10,20,R,0.0,27,None,None,24,17,1:30.579,Water leak

In [155]:
pd.DataFrame(results).to_csv('results.csv',index=False)

### pitStops

In [2]:
pitStops = {'year':[],"raceId":[],'driverId':[], 'stop':[],
           'lap':[], 'time':[], 'duration':[]}#, 'milliseconds':[]}

for year in range(2010,2023):
    url='http://ergast.com/api/f1' 
    url1=url+'/{}.json?limit=1000'
    url3=url+'/{}'.format(year)
    response = requests.get(url1.format(year))
    content=json.loads(response.content)
    tampath=len(content['MRData']['RaceTable']['Races'])
    links=[]
    for i in range(1,tampath+1):
        url2=url3+'/{}/pitstops.json?limit=1000'
        response = requests.get(url2.format(i))
        content=json.loads(response.content)
        links.append(url2.format(i))
    i=0 
    for j in links:
        try:
            response = requests.get(j)
            content=json.loads(response.content)
        except:
            print(f"Hay un error en {j}")
        try: 
            content['MRData']['RaceTable']['Races'][0]['PitStops']
            for item in content['MRData']['RaceTable']['Races'][0]['PitStops']:
                pitStops["raceId"].append(content['MRData']['RaceTable']['Races'][0]['round'])
                pitStops["year"].append(content['MRData']['RaceTable']['Races'][0]['season'])
                pitStops["driverId"].append(item['driverId'])
                pitStops["stop"].append(item['stop'])
                pitStops["lap"].append(item['lap'])
                pitStops["time"].append(item['time'])
                pitStops["duration"].append(item['duration'])
            
        except:
            print(f"Hay un error en {j}")
            
        

pitStopss=pd.DataFrame(pitStops)         
pitStopss.head()

Hay un error en http://ergast.com/api/f1/2010/1/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/2/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/3/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/4/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/5/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/6/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/7/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/8/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/9/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/10/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/11/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/12/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/13/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/14/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/15/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/16/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/17/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/18/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2010/19/pitstops.json?limit=1000
Hay un error en http://ergast.com/api/f1/2021/12/pitstops.json?limit=1000

   year raceId            driverId stop lap      time duration
0  2011      1         alguersuari    1   1  17:05:23   26.898
1  2011      1  michael_schumacher    1   1  17:05:52   25.021
2  2011      1              webber    1  11  17:20:48   23.426
3  2011      1              alonso    1  12  17:22:34   23.251
4  2011      1               massa    1  13  17:24:10   23.842

In [3]:
pd.DataFrame(pitStopss).to_csv('pitStopss.csv',index=False)

# Tarea 3
Crear script que genere archivos csv de las siguientes tablas:

lapTimes driverStandings constructorStandings constructorResults

### LapTimes

In [4]:
lapTimes={"year":[],"round":[],"raceId":[],"driverId":[],"lap":[],"position":[],"time":[]}

for year in range(2010,2023):
    url='http://ergast.com/api/f1' 
    url1=url+'/{}.json?limit=1000'
    url3=url+'/{}'.format(year)
    response = requests.get(url1.format(year))
    content=json.loads(response.content)
    tampath=len(content['MRData']['RaceTable']['Races'])
    links=[]
    for i in range(1,tampath+1):
        url2=url3+'/{}/laps.json?limit=10000'
        response = requests.get(url2.format(i))
        content=json.loads(response.content)
        links.append(url2.format(i))
    for j in links:
        print(j)
        response = requests.get(j)
        content=json.loads(response.content)
        for i in content['MRData']['RaceTable']["Races"][0]["Laps"]:
            for item in i['Timings']:
                try:
                    lapTimes["year"].append(content['MRData']['RaceTable']['Races'][0]['season'])                    
                except:
                    lapTimes["year"].append("")
                try:
                    lapTimes["round"].append(content['MRData']['RaceTable']['Races'][0]['round'])                    
                except:
                    lapTimes["round"].append("")
                try:
                    lapTimes["raceId"].append(content['MRData']['RaceTable']["Races"][0]['raceName'])
                except:
                    lapTimes["raceId"].append("")
                try:
                    lapTimes["driverId"].append(item['driverId'])
                except:
                    lapTimes["driverId"].append("")
                try:
                    lapTimes["lap"].append(i['number'])
                except:
                    lapTimes["lap"].append("")
                try:
                    lapTimes["position"].append(item['position'])
                except:
                    lapTimes["position"].append("")
                try:
                    lapTimes["time"].append(item['time'])
                except:
                    lapTimes["time"].append("")
                
lapTimess=pd.DataFrame.from_dict(lapTimes,orient='index')
lapTimess=lapTimess.transpose()

http://ergast.com/api/f1/2010/1/laps.json?limit=10000
http://ergast.com/api/f1/2010/2/laps.json?limit=10000
http://ergast.com/api/f1/2010/3/laps.json?limit=10000
http://ergast.com/api/f1/2010/4/laps.json?limit=10000
http://ergast.com/api/f1/2010/5/laps.json?limit=10000
http://ergast.com/api/f1/2010/6/laps.json?limit=10000
http://ergast.com/api/f1/2010/7/laps.json?limit=10000
http://ergast.com/api/f1/2010/8/laps.json?limit=10000
http://ergast.com/api/f1/2010/9/laps.json?limit=10000
http://ergast.com/api/f1/2010/10/laps.json?limit=10000
http://ergast.com/api/f1/2010/11/laps.json?limit=10000
http://ergast.com/api/f1/2010/12/laps.json?limit=10000
http://ergast.com/api/f1/2010/13/laps.json?limit=10000
http://ergast.com/api/f1/2010/14/laps.json?limit=10000
http://ergast.com/api/f1/2010/15/laps.json?limit=10000
http://ergast.com/api/f1/2010/16/laps.json?limit=10000
http://ergast.com/api/f1/2010/17/laps.json?limit=10000
http://ergast.com/api/f1/2010/18/laps.json?limit=10000
http://ergast.com/api/f1/2010/19/laps.json?limit=10000
http://ergast.com/api/f1/2011/1/laps.json?limit=10000
http://ergast.com/api/f1/2011/2/laps.json?limit=10000
http://ergast.com/api/f1/2011/3/laps.json?limit=10000
http://ergast.com/api/f1/2011/4/laps.json?limit=10000
http://ergast.com/api/f1/2011/5/laps.json?limit=10000
http://ergast.com/api/f1/2011/6/laps.json?limit=10000
http://ergast.com/api/f1/2011/7/laps.json?limit=10000
http://ergast.com/api/f1/2011/8/laps.json?limit=10000
http://ergast.com/api/f1/2011/9/laps.json?limit=10000
http://ergast.com/api/f1/2011/10/laps.json?limit=10000
http://ergast.com/api/f1/2011/11/laps.json?limit=10000
http://ergast.com/api/f1/2011/12/laps.json?limit=10000
http://ergast.com/api/f1/2011/13/laps.json?limit=10000
http://ergast.com/api/f1/2011/14/laps.json?limit=10000
http://ergast.com/api/f1/2011/15/laps.json?limit=10000
http://ergast.com/api/f1/2011/16/laps.json?limit=10000
http://ergast.com/api/f1/2011/17/laps.json?limit=10000
http://ergast.com/api/f1/2011/18/laps.json?limit=10000
http://ergast.com/api/f1/2011/19/laps.json?limit=10000
http://ergast.com/api/f1/2012/1/laps.json?limit=10000
http://ergast.com/api/f1/2012/2/laps.json?limit=10000
http://ergast.com/api/f1/2012/3/laps.json?limit=10000
http://ergast.com/api/f1/2012/4/laps.json?limit=10000
http://ergast.com/api/f1/2012/5/laps.json?limit=10000
http://ergast.com/api/f1/2012/6/laps.json?limit=10000
http://ergast.com/api/f1/2012/7/laps.json?limit=10000
http://ergast.com/api/f1/2012/8/laps.json?limit=10000
http://ergast.com/api/f1/2012/9/laps.json?limit=10000
http://ergast.com/api/f1/2012/10/laps.json?limit=10000
http://ergast.com/api/f1/2012/11/laps.json?limit=10000
http://ergast.com/api/f1/2012/12/laps.json?limit=10000
http://ergast.com/api/f1/2012/13/laps.json?limit=10000
http://ergast.com/api/f1/2012/14/laps.json?limit=10000
http://ergast.com/api/f1/2012/15/laps.json?limit=10000
http://ergast.com/api/f1/2012/16/laps.json?limit=10000
http://ergast.com/api/f1/2012/17/laps.json?limit=10000
http://ergast.com/api/f1/2012/18/laps.json?limit=10000
http://ergast.com/api/f1/2012/19/laps.json?limit=10000
http://ergast.com/api/f1/2012/20/laps.json?limit=10000
http://ergast.com/api/f1/2013/1/laps.json?limit=10000
http://ergast.com/api/f1/2013/2/laps.json?limit=10000
http://ergast.com/api/f1/2013/3/laps.json?limit=10000
http://ergast.com/api/f1/2013/4/laps.json?limit=10000
http://ergast.com/api/f1/2013/5/laps.json?limit=10000
http://ergast.com/api/f1/2013/6/laps.json?limit=10000
http://ergast.com/api/f1/2013/7/laps.json?limit=10000
http://ergast.com/api/f1/2013/8/laps.json?limit=10000
http://ergast.com/api/f1/2013/9/laps.json?limit=10000
http://ergast.com/api/f1/2013/10/laps.json?limit=10000
http://ergast.com/api/f1/2013/11/laps.json?limit=10000
http://ergast.com/api/f1/2013/12/laps.json?limit=10000
http://ergast.com/api/f1/2013/13/laps.json?limit=10000
http://ergast.com/api/f1/2013/14/laps.json?limit=10000
http://ergast.com/api/f1/2013/15/laps.json?limit=10000
http://ergast.com/api/f1/2013/16/laps.json?limit=10000
http://ergast.com/api/f1/2013/17/laps.json?limit=10000
http://ergast.com/api/f1/2013/18/laps.json?limit=10000
http://ergast.com/api/f1/2013/19/laps.json?limit=10000
http://ergast.com/api/f1/2014/1/laps.json?limit=10000
http://ergast.com/api/f1/2014/2/laps.json?limit=10000
http://ergast.com/api/f1/2014/3/laps.json?limit=10000
http://ergast.com/api/f1/2014/4/laps.json?limit=10000
http://ergast.com/api/f1/2014/5/laps.json?limit=10000
http://ergast.com/api/f1/2014/6/laps.json?limit=10000
http://ergast.com/api/f1/2014/7/laps.json?limit=10000
http://ergast.com/api/f1/2014/8/laps.json?limit=10000
http://ergast.com/api/f1/2014/9/laps.json?limit=10000
http://ergast.com/api/f1/2014/10/laps.json?limit=10000
http://ergast.com/api/f1/2014/11/laps.json?limit=10000
http://ergast.com/api/f1/2014/12/laps.json?limit=10000
http://ergast.com/api/f1/2014/13/laps.json?limit=10000
http://ergast.com/api/f1/2014/14/laps.json?limit=10000
http://ergast.com/api/f1/2014/15/laps.json?limit=10000
http://ergast.com/api/f1/2014/16/laps.json?limit=10000
http://ergast.com/api/f1/2014/17/laps.json?limit=10000
http://ergast.com/api/f1/2014/18/laps.json?limit=10000
http://ergast.com/api/f1/2014/19/laps.json?limit=10000
http://ergast.com/api/f1/2015/1/laps.json?limit=10000
http://ergast.com/api/f1/2015/2/laps.json?limit=10000
http://ergast.com/api/f1/2015/3/laps.json?limit=10000
http://ergast.com/api/f1/2015/4/laps.json?limit=10000
http://ergast.com/api/f1/2015/5/laps.json?limit=10000
http://ergast.com/api/f1/2015/6/laps.json?limit=10000
http://ergast.com/api/f1/2015/7/laps.json?limit=10000
http://ergast.com/api/f1/2015/8/laps.json?limit=10000
http://ergast.com/api/f1/2015/9/laps.json?limit=10000
http://ergast.com/api/f1/2015/10/laps.json?limit=10000
http://ergast.com/api/f1/2015/11/laps.json?limit=10000
http://ergast.com/api/f1/2015/12/laps.json?limit=10000
http://ergast.com/api/f1/2015/13/laps.json?limit=10000
http://ergast.com/api/f1/2015/14/laps.json?limit=10000
http://ergast.com/api/f1/2015/15/laps.json?limit=10000
http://ergast.com/api/f1/2015/16/laps.json?limit=10000
http://ergast.com/api/f1/2015/17/laps.json?limit=10000
http://ergast.com/api/f1/2015/18/laps.json?limit=10000
http://ergast.com/api/f1/2015/19/laps.json?limit=10000
http://ergast.com/api/f1/2016/1/laps.json?limit=10000
http://ergast.com/api/f1/2016/2/laps.json?limit=10000
http://ergast.com/api/f1/2016/3/laps.json?limit=10000
http://ergast.com/api/f1/2016/4/laps.json?limit=10000
http://ergast.com/api/f1/2016/5/laps.json?limit=10000
http://ergast.com/api/f1/2016/6/laps.json?limit=10000
http://ergast.com/api/f1/2016/7/laps.json?limit=10000
http://ergast.com/api/f1/2016/8/laps.json?limit=10000
http://ergast.com/api/f1/2016/9/laps.json?limit=10000
http://ergast.com/api/f1/2016/10/laps.json?limit=10000
http://ergast.com/api/f1/2016/11/laps.json?limit=10000
http://ergast.com/api/f1/2016/12/laps.json?limit=10000
http://ergast.com/api/f1/2016/13/laps.json?limit=10000
http://ergast.com/api/f1/2016/14/laps.json?limit=10000
http://ergast.com/api/f1/2016/15/laps.json?limit=10000
http://ergast.com/api/f1/2016/16/laps.json?limit=10000
http://ergast.com/api/f1/2016/17/laps.json?limit=10000
http://ergast.com/api/f1/2016/18/laps.json?limit=10000
http://ergast.com/api/f1/2016/19/laps.json?limit=10000
http://ergast.com/api/f1/2016/20/laps.json?limit=10000
http://ergast.com/api/f1/2016/21/laps.json?limit=10000
http://ergast.com/api/f1/2017/1/laps.json?limit=10000
http://ergast.com/api/f1/2017/2/laps.json?limit=10000
http://ergast.com/api/f1/2017/3/laps.json?limit=10000
http://ergast.com/api/f1/2017/4/laps.json?limit=10000
http://ergast.com/api/f1/2017/5/laps.json?limit=10000
http://ergast.com/api/f1/2017/6/laps.json?limit=10000
http://ergast.com/api/f1/2017/7/laps.json?limit=10000
http://ergast.com/api/f1/2017/8/laps.json?limit=10000
http://ergast.com/api/f1/2017/9/laps.json?limit=10000
http://ergast.com/api/f1/2017/10/laps.json?limit=10000
http://ergast.com/api/f1/2017/11/laps.json?limit=10000
http://ergast.com/api/f1/2017/12/laps.json?limit=10000
http://ergast.com/api/f1/2017/13/laps.json?limit=10000
http://ergast.com/api/f1/2017/14/laps.json?limit=10000
http://ergast.com/api/f1/2017/15/laps.json?limit=10000

http://ergast.com/api/f1/2017/16/laps.json?limit=10000
http://ergast.com/api/f1/2017/17/laps.json?limit=10000
http://ergast.com/api/f1/2017/18/laps.json?limit=10000
http://ergast.com/api/f1/2017/19/laps.json?limit=10000
http://ergast.com/api/f1/2017/20/laps.json?limit=10000
http://ergast.com/api/f1/2018/1/laps.json?limit=10000
http://ergast.com/api/f1/2018/2/laps.json?limit=10000
http://ergast.com/api/f1/2018/3/laps.json?limit=10000
http://ergast.com/api/f1/2018/4/laps.json?limit=10000
http://ergast.com/api/f1/2018/5/laps.json?limit=10000
http://ergast.com/api/f1/2018/6/laps.json?limit=10000
http://ergast.com/api/f1/2018/7/laps.json?limit=10000
http://ergast.com/api/f1/2018/8/laps.json?limit=10000
http://ergast.com/api/f1/2018/9/laps.json?limit=10000
http://ergast.com/api/f1/2018/10/laps.json?limit=10000
http://ergast.com/api/f1/2018/11/laps.json?limit=10000
http://ergast.com/api/f1/2018/12/laps.json?limit=10000
http://ergast.com/api/f1/2018/13/laps.json?limit=10000
http://ergast.com/api/f1/2018/14/laps.json?limit=10000
http://ergast.com/api/f1/2018/15/laps.json?limit=10000
http://ergast.com/api/f1/2018/16/laps.json?limit=10000
http://ergast.com/api/f1/2018/17/laps.json?limit=10000
http://ergast.com/api/f1/2018/18/laps.json?limit=10000
http://ergast.com/api/f1/2018/19/laps.json?limit=10000
http://ergast.com/api/f1/2018/20/laps.json?limit=10000
http://ergast.com/api/f1/2018/21/laps.json?limit=10000
http://ergast.com/api/f1/2019/1/laps.json?limit=10000
http://ergast.com/api/f1/2019/2/laps.json?limit=10000
http://ergast.com/api/f1/2019/3/laps.json?limit=10000
http://ergast.com/api/f1/2019/4/laps.json?limit=10000
http://ergast.com/api/f1/2019/5/laps.json?limit=10000
http://ergast.com/api/f1/2019/6/laps.json?limit=10000
http://ergast.com/api/f1/2019/7/laps.json?limit=10000
http://ergast.com/api/f1/2019/8/laps.json?limit=10000
http://ergast.com/api/f1/2019/9/laps.json?limit=10000
http://ergast.com/api/f1/2019/10/laps.json?limit=10000
http://ergast.com/api/f1/2019/11/laps.json?limit=10000
http://ergast.com/api/f1/2019/12/laps.json?limit=10000
http://ergast.com/api/f1/2019/13/laps.json?limit=10000
http://ergast.com/api/f1/2019/14/laps.json?limit=10000
http://ergast.com/api/f1/2019/15/laps.json?limit=10000
http://ergast.com/api/f1/2019/16/laps.json?limit=10000
http://ergast.com/api/f1/2019/17/laps.json?limit=10000
http://ergast.com/api/f1/2019/18/laps.json?limit=10000
http://ergast.com/api/f1/2019/19/laps.json?limit=10000
http://ergast.com/api/f1/2019/20/laps.json?limit=10000
http://ergast.com/api/f1/2019/21/laps.json?limit=10000
http://ergast.com/api/f1/2020/1/laps.json?limit=10000
http://ergast.com/api/f1/2020/2/laps.json?limit=10000
http://ergast.com/api/f1/2020/3/laps.json?limit=10000
http://ergast.com/api/f1/2020/4/laps.json?limit=10000
http://ergast.com/api/f1/2020/5/laps.json?limit=10000
http://ergast.com/api/f1/2020/6/laps.json?limit=10000
http://ergast.com/api/f1/2020/7/laps.json?limit=10000
http://ergast.com/api/f1/2020/8/laps.json?limit=10000
http://ergast.com/api/f1/2020/9/laps.json?limit=10000
http://ergast.com/api/f1/2020/10/laps.json?limit=10000
http://ergast.com/api/f1/2020/11/laps.json?limit=10000
http://ergast.com/api/f1/2020/12/laps.json?limit=10000
http://ergast.com/api/f1/2020/13/laps.json?limit=10000
http://ergast.com/api/f1/2020/14/laps.json?limit=10000
http://ergast.com/api/f1/2020/15/laps.json?limit=10000
http://ergast.com/api/f1/2020/16/laps.json?limit=10000
http://ergast.com/api/f1/2020/17/laps.json?limit=10000
http://ergast.com/api/f1/2021/1/laps.json?limit=10000
http://ergast.com/api/f1/2021/2/laps.json?limit=10000
http://ergast.com/api/f1/2021/3/laps.json?limit=10000
http://ergast.com/api/f1/2021/4/laps.json?limit=10000
http://ergast.com/api/f1/2021/5/laps.json?limit=10000
http://ergast.com/api/f1/2021/6/laps.json?limit=10000
http://ergast.com/api/f1/2021/7/laps.json?limit=10000
http://ergast.com/api/f1/2021/8/laps.json?limit=10000
http://ergast.com/api/f1/2021/9/laps.json?limit=10000
http://ergast.com/api/f1/2021/10/laps.json?limit=10000
http://ergast.com/api/f1/2021/11/laps.json?limit=10000
http://ergast.com/api/f1/2021/12/laps.json?limit=10000
http://ergast.com/api/f1/2021/13/laps.json?limit=10000
http://ergast.com/api/f1/2021/14/laps.json?limit=10000
http://ergast.com/api/f1/2021/15/laps.json?limit=10000
http://ergast.com/api/f1/2021/16/laps.json?limit=10000
http://ergast.com/api/f1/2021/17/laps.json?limit=10000
http://ergast.com/api/f1/2021/18/laps.json?limit=10000
http://ergast.com/api/f1/2021/19/laps.json?limit=10000
http://ergast.com/api/f1/2021/20/laps.json?limit=10000
http://ergast.com/api/f1/2021/21/laps.json?limit=10000
http://ergast.com/api/f1/2021/22/laps.json?limit=10000
http://ergast.com/api/f1/2022/1/laps.json?limit=10000
http://ergast.com/api/f1/2022/2/laps.json?limit=10000
http://ergast.com/api/f1/2022/3/laps.json?limit=10000
http://ergast.com/api/f1/2022/4/laps.json?limit=10000
http://ergast.com/api/f1/2022/5/laps.json?limit=10000
http://ergast.com/api/f1/2022/6/laps.json?limit=10000
http://ergast.com/api/f1/2022/7/laps.json?limit=10000
http://ergast.com/api/f1/2022/8/laps.json?limit=10000
http://ergast.com/api/f1/2022/9/laps.json?limit=10000
http://ergast.com/api/f1/2022/10/laps.json?limit=10000
http://ergast.com/api/f1/2022/11/laps.json?limit=10000
http://ergast.com/api/f1/2022/12/laps.json?limit=10000
http://ergast.com/api/f1/2022/13/laps.json?limit=10000
http://ergast.com/api/f1/2022/14/laps.json?limit=10000
http://ergast.com/api/f1/2022/15/laps.json?limit=10000
http://ergast.com/api/f1/2022/16/laps.json?limit=10000
http://ergast.com/api/f1/2022/17/laps.json?limit=10000
http://ergast.com/api/f1/2022/18/laps.json?limit=10000
http://ergast.com/api/f1/2022/19/laps.json?limit=10000
http://ergast.com/api/f1/2022/20/laps.json?limit=10000
http://ergast.com/api/f1/2022/21/laps.json?limit=10000
http://ergast.com/api/f1/2022/22/laps.json?limit=10000

        year round                raceId   driverId lap position      time
0       2010     1    Bahrain Grand Prix     vettel   1        1  2:03.366
1       2010     1    Bahrain Grand Prix     alonso   1        2  2:05.394
2       2010     1    Bahrain Grand Prix      massa   1        3  2:06.758
3       2010     1    Bahrain Grand Prix    rosberg   1        4  2:08.063
4       2010     1    Bahrain Grand Prix   hamilton   1        5  2:08.558
...      ...   ...                   ...        ...  ..      ...       ...
291843  2022    22  Abu Dhabi Grand Prix       ocon  58        7  1:30.021
291844  2022    22  Abu Dhabi Grand Prix     stroll  58        8  1:31.330
291845  2022    22  Abu Dhabi Grand Prix  ricciardo  58        9  1:30.856
291846  2022    22  Abu Dhabi Grand Prix     vettel  58       10  1:30.351
291847  2022    22  Abu Dhabi Grand Prix    tsunoda  58       11  1:32.280

[291848 rows x 7 columns]

In [5]:
lapTimess

        year round                raceId   driverId lap position      time
0       2010     1    Bahrain Grand Prix     vettel   1        1  2:03.366
1       2010     1    Bahrain Grand Prix     alonso   1        2  2:05.394
2       2010     1    Bahrain Grand Prix      massa   1        3  2:06.758
3       2010     1    Bahrain Grand Prix    rosberg   1        4  2:08.063
4       2010     1    Bahrain Grand Prix   hamilton   1        5  2:08.558
...      ...   ...                   ...        ...  ..      ...       ...
291843  2022    22  Abu Dhabi Grand Prix       ocon  58        7  1:30.021
291844  2022    22  Abu Dhabi Grand Prix     stroll  58        8  1:31.330
291845  2022    22  Abu Dhabi Grand Prix  ricciardo  58        9  1:30.856
291846  2022    22  Abu Dhabi Grand Prix     vettel  58       10  1:30.351
291847  2022    22  Abu Dhabi Grand Prix    tsunoda  58       11  1:32.280

[291848 rows x 7 columns]

In [6]:
lapTimess.to_csv('lapTimess.csv',index=False)

### driverStandings

In [24]:
driverStandings={"year":[],'driverStandingsId':[],"driverId":[],"points":[],'position':[],'positionText':[],'wins':[]}

for year in range(2010,2023):
    url= 'http://ergast.com/api/f1/{}/driverStandings.json?limit=1000'
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    inicio=content['MRData']['StandingsTable']['StandingsLists']
    for item in range(0,len(inicio)):
        for item2 in content['MRData']['StandingsTable']['StandingsLists'][item]['DriverStandings']:
            driverStandings['year'].append(year)
            #driverStandings['raceId'].append(year)
            driverStandings['driverId'].append(item2['Driver']['driverId'])
            driverStandings['points'].append(item2['points'])
            driverStandings['position'].append(item2['position'])
            driverStandings['positionText'].append(item2['positionText'])
            driverStandings['wins'].append(item2['wins'])
driverStandings['driverStandingsId']=np.arange(1,305,1)
pd.DataFrame(driverStandings)

     year  driverStandingsId    driverId points position positionText wins
0    2010                  1      vettel    256        1            1    5
1    2010                  2      alonso    252        2            2    5
2    2010                  3      webber    242        3            3    4
3    2010                  4    hamilton    240        4            4    3
4    2010                  5      button    214        5            5    2
..    ...                ...         ...    ...      ...          ...  ...
299  2022                300        zhou      6       18           18    0
300  2022                301       albon      4       19           19    0
301  2022                302      latifi      2       20           20    0
302  2022                303    de_vries      2       21           21    0
303  2022                304  hulkenberg      0       22           22    0

[304 rows x 7 columns]

In [25]:
pd.DataFrame(driverStandings).to_csv('driverStandings.csv',index=False)

### constructorStandings

In [60]:
constructorStandings={"year":[],'constructorStandingsId':[],"constructorId":[],"points":[],'position':[],'positionText':[],'wins':[]}

for year in range(2010,2023):
    url= 'http://ergast.com/api/f1/{}/constructorStandings.json?limit=1000'
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    inicio=content['MRData']['StandingsTable']['StandingsLists']
    for item in range(0,len(inicio)):
        for item2 in content['MRData']['StandingsTable']['StandingsLists'][item]['ConstructorStandings']:
            constructorStandings['year'].append(year)
            #constructorStandings['raceId'].append(year)
            constructorStandings['constructorId'].append(item2['Constructor']['constructorId'])
            constructorStandings['points'].append(item2['points'])
            constructorStandings['position'].append(item2['position'])
            constructorStandings['positionText'].append(item2['positionText'])
            constructorStandings['wins'].append(item2['wins'])
constructorStandings['constructorStandingsId']=np.arange(1,140,1)
pd.DataFrame(constructorStandings)

,year,constructorStandingsId,constructorId,points,position,positionText,wins
0,2010,1,red_bull,498,1,1,9
1,2010,2,mclaren,454,2,2,5
2,2010,3,ferrari,396,3,3,5
3,2010,4,mercedes,214,4,4,0
4,2010,5,renault,163,5,5,0
...,...,...,...,...,...,...,...
134,2022,135,alfa,55,6,6,0
135,2022,136,aston_martin,55,7,7,0
136,2022,137,haas,37,8,8,0
137,2022,138,alphatauri,35,9,9,0
138,2022,139,williams,8,10,10,0

In [61]:
pd.DataFrame(constructorStandings).to_csv('constructorStandings.csv',index=False)

### constructorResults

In [63]:
constructorResults = {'year':[],'constructorResultsId':[], 
           'raceId':[], 'constructorId':[],'status':[]}
for year in range(2010,2023):
    url= 'http://ergast.com/api/f1/{}/results.json?limit=1000'
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    for item in range(0,len(content['MRData']['RaceTable']['Races'])):
        for item2 in content['MRData']['RaceTable']['Races'][item]['Results']:
            constructorResults['year'].append(year)
            constructorResults['raceId'].append(content['MRData']['RaceTable']['Races'][item]['raceName'])
            constructorResults['constructorId'].append(item2['Constructor']['constructorId'])
            constructorResults['status'].append(item2['status'])
constructorResults['constructorResultsId']=np.arange(1,5518,1)
pd.DataFrame(constructorResults)

,year,constructorResultsId,raceId,constructorId,status
0,2010,1,Bahrain Grand Prix,ferrari,Finished
1,2010,2,Bahrain Grand Prix,ferrari,Finished
2,2010,3,Bahrain Grand Prix,mclaren,Finished
3,2010,4,Bahrain Grand Prix,red_bull,Finished
4,2010,5,Bahrain Grand Prix,mercedes,Finished
...,...,...,...,...,...
5512,2022,5513,Abu Dhabi Grand Prix,haas,+1 Lap
5513,2022,5514,Abu Dhabi Grand Prix,haas,+1 Lap
5514,2022,5515,Abu Dhabi Grand Prix,mercedes,Hydraulics
5515,2022,5516,Abu Dhabi Grand Prix,williams,Collision damage
5516,2022,5517,Abu Dhabi Grand Prix,alpine,Water leak

In [64]:
pd.DataFrame(constructorResults).to_csv('constructorResults.csv',index=False)